using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebService.Asmx
{
    public static class Dummy
    {
        public static int Next(int about)
        {
            Random random = new Random();
            var res = random.Next(1,about);
            return res;
        }
        public static string RandomString(int length)
        {
            Random random = new Random();
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        public static string ProductName()
        {
            return ProductNames[Next(ProductNames.Count)];
        }

        public static string Color()
        {
            return Colors[Next(Colors.Count)];
        }

        public static int Size()
        {
            return Next(100);
        }
        public static double Price(int about)
        {
            return Next(about) + (double)Next(100) / 100;
        }

        private static List<string> Colors = new List<string>()
        {
            "KIRMIZI",
            "MAVİ",
            "MOR",
            "SARI",
            "YEŞİL",
            "SİYAH",
            "BEYAZ",
            "LACİVERT",
            "KAHVERENGİ",
            "TURUNCU",
            "PEMBE",
            "BORDO"
        };
        private static List<string> ProductNames = new List<string>()
        {
            "1 L AYÇİÇEK YAĞI",
            "2 LT AYÇİÇEK YAĞI",
            "3 L AYÇİÇEK YAĞI",
            "5 L TNK. AYÇİÇEK YAĞI",
            "5 L PET AYÇİÇEK YAĞI",
            "10 L AYÇİÇEK YAĞI",
            "18 L AYÇİÇEK YAĞI",
            "BİZİM AYÇİÇEK  ",
            "ONA AYÇİÇEK YAĞI 1 LT",
            "ONA AYÇİÇEK YAĞI 1 LT 6'LI SHRINK",
            "ONA AYÇİÇEK YAĞI 2 LT",
            "ONA AYÇİÇEK YAĞI 3 LT",
            "ONA AYÇİÇEK YAĞI 5 LT",
            "ONA AYÇİÇEK YAĞI 5 LT Pet",
            "ONA AYÇİÇEK YAĞI 10 LT",
            "ONA AYÇİÇEK YAĞI 18 LT",
            "ONA AYÇİÇEK  ",
            "1 LMISIRYAĞI",
            "2 LMISIRYAĞI",
            "3 LMISIRYAĞI",
            "5 L TNK.MISIRYAĞI",
            "5 L PET.MISIRYAĞI",
            "10 LMISIRYAĞI",
            "18 LMISIRYAĞI",
            "BİZİM MISIR YAĞI",
            "LUNA MISIR YAĞI 1 LT",
            "LUNA MISIR YAĞI 2 LT",
            "LUNA MISIR YAĞI 3 LT",
            "LUNA MISIR YAĞI 5 LT ",
            "LUNA MISIR YAĞI 5 LT Pet",
            "LUNA MISIR YAĞI 10 LT",
            "LUNA MISIR YAĞI 18 LT",
            "LUNA MISIRYAĞI",
            "SOYOLA 1 LT",
            "SOYOLA 2 LT",
            "SOYOLA 5 LT",
            "SOYALA",
            "KANOLA",
            "1/2  L RİVİERA ALTIN HASAT ZEYTİNYAĞI",
            "1 L RİVİERA ALTIN HASAT ZEYTİNYAĞI",
            "2 L RİVİERA ALTIN HASAT ZEYTİNYAĞI",
            "5 L RİVİERA ALTIN HASAT ZEYTİNYAĞI",
            "ALTIN HASAT RİVİERA ZEYTİNYAĞI",
            "RIVIERA 1 LT",
            "RIVIERA 2 LT",
            "RIVIERA 5 LT",
            "LUNA RİVİERA",
            "1/2 L EKSTR NATUREL SIZMA ZEYTİNYAĞI",
            "1 L SIZMA ALTIN HASAT ZEYTİNYAĞI",
            "2 L SIZMA ALTIN HASAT ZEYTİNYAĞI",
            "5 L SIZMA ALTIN HASAT ZEYTİNYAĞI",
            "ALTIN HASAT SIZMA ZEYTİNYAĞI",
            "SIZMA 1 LT",
            "SIZMA 2 LT",
            "SIZMA 5 LT",
            "LUNA SIZMA",
            "BİZİM PKT. MARGARİN",
            "BİZİM 6 AL 5 ÖDE EKONOMİK PKT.",
            "BİZİM 4 LÜ EKO PAKET",
            "BİZİM PAKET",
            "TEREM PKT. MARGAR.N",
            "3'LÜ TEREMYAĞ FLOWPACK %15 EKONOMİK",
            "TEREM PKT.MARG. 4 AL 3 ÖDE ",
            "TEREM PAKET",
            "KALBİM NORMAL PAKET MARG.",
            "KALBİM ZEYTİNYAĞLI PAKET MARG.",
            "KALBİM STİCK PAKET",
            "LUNA PAKET",
            "LUNA PAKET 4lü",
            "LUNA PAKET 6lı",
            "LUNA PAKET MARGARİN",
            "LUNA TEREYAĞI LEZZETİ PAKET",
            "LUNA TEREYAĞI LEZZETİ PAKET 4lü",
            "LUNA TEREYAĞI LEZZETİ PAKET 6'lı",
            "LUNA TEREYAĞI LEZZETİ PAKET MARGARİN",
            "HUNER MARGARIN",
            "HUNER MARGARIN 4lü",
            "HÜNER MARGARİN",
            "H. SABAH PAKET",
            "H. SABAH PAKET 4LÜ",
            "H. SABAH PAKET 6LI",
            "H. SABAH PAKET",
            "LUNA SIZMA ZEYT. YAĞLI PK 250 GR",
            "LUNA SIZMA ZEYT. YAĞLI PAKET MARGARİN",
            "250g BİZİM KAHVALTILIK KASE MARG.",
            "500g BİZİM KAHVALTILIK KASE MARG.",
            "250g BİZİM ÇİLEK REÇELLİ KASE MARG.",
            "BİZİM KASE",
            "250g BİZİM KASE MARG.",
            "500g BİZİM KASE MARG.",
            "1000g BİZİM KASE MARG.",
            "BİZİM KASE",
            "LUNA KASE 250 G",
            "LUNA KASE 500 G",
            "LUNA KASE",
            "250gTEREM KASE MARG.",
            "500 gTEREM KASE MARG.",
            "250 g TEREM BALLI YAĞ ",
            "500 g TEREM BALLI YAĞ ",
            "TEREM KASE",
            "LUNA TEREYAĞI LEZZETİ KASE 250 GR",
            "LUNA TEREYAĞI LEZZETİ KASE 500 GR",
            "LUNA TEREYAĞI LEZZETİ KASE ",
            "LUNA SIZMA ZEYT. YAĞLI KASE 250 GR",
            "LUNA SIZMA ZEYT. YAĞLI KASE ",
            "H.SABAH KASE",
            "H.SABAH KASE",
            "250g KALBİM KASE MARGARİN",
            "500g KALBİM KASE MARGARİN",
            "250g KALBİM ZEYTİNYAĞLI KASE MARGARİN",
            "250g KALBİM ZEYTİNYAĞLI KASE MARGARİN",
            "KALBİM KASE",
            "250 GR KALBİM BENECOL KASE MARGARİN",
            "KALBİM BENECOL ",
            "5 KG. BİZİM BEREKET",
            "10 KG. BİZİM BEREKET",
            "18 KG. BİZİM BEREKET",
            "BEREKET",
            "EVET 2 KG",
            "EVET 5 KG",
            "EVET 10 KG",
            "EVET 18 KG",
            "EVET",
            "H.SABAH 10 KG",
            "H.SABAH 18 KG",
            "H SABAH",
            "V.SABAH 2 KG",
            "EXTRA SABAH 5 KG KUTU",
            "EXTRA SABAH 5 KG KASE",
            "EVET",
            "1/5 L SLİM TETRA SÜT",
            "1/5X6 SLİM TETRA SÜT",
            "1/2 LT İÇİM SÜT",
            "1/1 L KAPAKLI İÇİM SÜT",
            "1/1X4 SHRİNK KAPAKLI SÜT",
            "İÇİM SÜT 2 LT. COMBİBLOC TETRA SÜT",
            "TETRAPAK SADE SÜT",
            "1/2X6 SHRINK ŞİŞE SÜT",
            "1/1X6 SHRINK ŞİŞE SÜT",
            "1/1X6 BASKILI ŞİŞE SÜT",
            "1500 ML. İÇİM ŞİŞE SÜT SHIRINK",
            "ŞİŞE SÜT",
            "1/5 L ALPELLA ÇİK. SÜT",
            "1/5 L MUZLU İÇİM SÜT",
            "1/5 L ÇİLEKLİ İÇİM SÜT",
            "1/5 L İÇİM VAN. BALLI SÜT",
            "1/5 L İÇİM ÇİKOLATALI SÜT",
            "1/5 L İÇİM ŞEFTALİ AROMALI SÜT",
            "COCO POPS ÇİKOLATALI SÜT 200MLx27",
            "1/5X6 MUZLU SHRİNK SÜT",
            "1/5X6 ÇİLEKLİ SHRİNK SÜT",
            "1/5X6 ALP. ÇİK. SHRİNK SÜT",
            "1/5X6 İÇİM ÇİK. SHRİNK SÜT",
            "1/5X6 VANİLYA BALLI SÜT",
            "1/2 ALPELLA SÜT",
            "AROMALI SÜT",
            "1/1 LAKTAZ SÜT",
            "1 LT LAKTOZSUZ YARIM YAĞLI SÜT",
            "1/2 L EXTRA LIGHT SÜT",
            "1/1 LT. İÇİM LIGHT SÜT",
            "1/2 LT. KALBİM BENECOL SÜT",
            "ÖZEL SÜT",
            "İÇİM ÇİLEKLİ PUDİNG",
            "İÇİM MUZLU PUDİNG",
            "İÇİM ÇİKOLATALI PUDİNG 1/2 LT",
            "ALPELLA ÇİK. PUDİNG",
            "ALPELLA TETRA PUDİNG",
            "TETRA PUDİNG ",
            "ALPELLA   ÇİK. KASE PUD.",
            "ALPELLA  ÇİK. ÇİLEKLİ. KASE PUD.",
            "ALPELLA ÇİK. KARAMELLİ KASE PUD.",
            "ALPELLA ÇİK. KESTANELİ KASE PUD.",
            "ALPELLA KASE PUDİNG T.ÜSTÜ STAND 4 ÇEŞİT",
            "KASE PUDİNG",
            "İÇİM TOZ PUD.MUZLU 125 GR YENİ DİZAYN",
            "İÇİM TOZ PUD.ÇİLEKLİ 125 GR YENİ DİZAYN",
            "İÇİM T.PUD.KAKAOLU 150 GR YENİ DİZAYN",
            "İÇİM T.PUD.KAK.FIN.150 GR YENİ DİZAYN",
            "İÇİM T.PUD.VANİLYALI 125 GR YENİ DİZAYN",
            "İÇİM T.PUD.BİTTER 115 GR YENİ DİZAYN",
            "İÇİM T.PUD.ÇİKOLATA.150 GR YENİ DİZAYN",
            "İÇİM TOZ PUDİNG KAKA. 4x150x18 (4AL3ÖDE)",
            "İÇİM TOZ PUDİNG",
            "PİYALE KAKAOLU PUD.24 * 150 GR. Tic.   ",
            "PİYALE MUZ AROMALI PUD.24 * 125 GR. Tic.",
            "PİYALE ÇİLEK AROM.PUD.24 * 125 GR. Tic. ",
            "PİYALE ÇİK.AROM.PUD.24 * 150 GR. Tic.   ",
            "PİYALE FINDIK.AROM.PUD.24 * 150 GR. Tic.",
            "PİYALE ÇİK.PARÇALI PUD.24 * 115 GR. Tic.   ",
            "PİYALE KAKAOLU PUD.(4 AL 3 ÖDE)",
            "PİYALE ÇİKOLATA AROM.PUD.(4 AL 3 ÖDE)",
            "PİYALE TOZ PUDİNG",
            "İÇİM SUPANGLE",
            "İÇİM SAKIZLI MUHALLEBİ",
            "İÇİM KEŞKÜL",
            "İÇİM AŞURE",
            "İÇİM KAZANDİBİ",
            "İÇİM İRMİK TATLISI",
            "İÇİM SÜTLAÇ",
            "İÇİM REVANİ",
            "İÇİM TAVUK GÖĞSÜ",
            "İÇİM İRMİK HELVASI",
            "İÇİM ÇİKOLATALI SOS",
            "İÇİM KAZANDİBİ 60 LI STAND KOLİ",
            "İÇİM TOZ TATLI",
            "PİYALE SUPANGLE 24*160 GR.",
            "PİYALE KAZANDİBİ 24*150 GR.",
            "PİYALE KEŞKÜL 24*150 GR.",
            "PİYALE SÜTLAÇ 24*157 GR.",
            "PİYALE AŞURE 24*225 GR.",
            "PİYALE İRMİK TATLISI 24*160 GR.",
            "PİYALE SADE MUHALLEBİ 24*195 GR.",
            "PİYALE TAVUK GÖĞSÜ 24*125 GR.",
            "PİYALE SAKIZLI MUHALLEBİ 24*140 GR.",
            "PİYALE REVANİ 12*500 GR.",
            "PİYALE İRMİK HELVASI 12*400 GR.",
            "PİYALE TOZ TATLI",
            "İÇİM TOZ KREM ŞANTİ",
            "İÇİM ÇİKOLATALI TOZ K.ŞANTİ",
            "İÇİM TOZ KREM ŞANTİ 75 gr",
            "İÇİM ÇİKOLATALI TOZ K.ŞANTİ 75 gr",
            "İÇİM KREM ŞANTİ",
            "PİYALE KREM ŞANTİ SADE 2X75 GR.",
            "PİYALE KREM ŞANTİ",
            "İÇİM HAZIR SAHLEP",
            "SIVI SAHLEP",
            "EZOGELIN ÇORBASI",
            "MERCİMEK ÇORBASI",
            "KREMALI TAVUK ÇORBASI",
            "ŞEHRIYELI TAVUK ÇORBASI",
            "DOMATES ÇORBASI",
            "İŞKEMBE ÇORBASI",
            "TARHANA ÇORBASI",
            "YAYLA ÇORBASI",
            "KREMALI SEBZE ÇORBASI",
            "KREMALI MANTAR ÇORBASI",
            "BİZİM MUTFAK ALTI SEBZE ÇORB.79GRx12x12",
            "BİZİM MUTFAK DOMAT. KES.ÇOR.99GRx12x12",
            "BİZİM MUTFAK SÜLEYMANİYE ÇORB.68GRx12x12",
            "BİZİM MUTFAK ET SU.TER.ŞEH.ÇO.87GRx12x12",
            "BM EZOGELİN ÇORBA 3+1 MULTIPACK ",
            "BM KR. TAVUK ÇORBA 3+1 MULTIPACK ",
            "BM MANTAR ÇORBA 3+1 MULTIPACK ",
            "ÇORBA BAKKAL KARMA KOLİ",
            "BİZİM MUTFAK KRE.TAV.ÇORB.62GRx72 RAM.Ö.",
            "BİZİM MUTFAK MERCİM.ÇORB.65GRx72 RAM.ÖZ.",
            "BİZİM MUTFAK TARHANA ÇORB.65GRx72 RAM.Ö.",
            "B. MUTFAK BAKKAL KARMA KL",
            "BM HAZIR ÇORBA",
            "PİYALE EZOGELİN 70 GR",
            "PİYALE KREMALİ  MANTAR 65 GR",
            "PİYALE ISKEMBE 65 GR",
            "PİYALE KREMALI DOMATES 65 GR",
            "PİYALE YAYLA 70 GR",
            "PİYALE KREMALİ TAVUK 65 GR",
            "PİYALE MERCİMEK 70 GR",
            "PİYALE SEHRİYELİ TAVUK 70 GR",
            "PİYALE TARHANA 70 GR",
            "PİYALE HAZIR ÇORBA",
            "BİZİM MUTFAK EKŞİLİ YUVALAMA ÇORBASI 72 Lİ",
            "BİZİM MUTFAK KELLE PAÇA ÇORBASI 72 Lİ",
            "BİZİM MUTFAK ANADOLU ÇORBASI 72 Lİ",
            "BİZİM MUTFAK DOMATESLİ BUĞDAY ÇORBASI",
            "BİZİM MUTFAK ISPANAKLI&BUĞDAYLI",
            "BİZİM MUTFAK YÜKSÜK ÇORBASI",
            "BM SPESİYAL ÇOR.TUTMAÇ 85 GRX12X6",
            "BM SPESİYAL MANTI ÇORBASI 100GRX12X6",
            "BM SPESİYAL ÇOR.KEŞKEK 85 GRX12X6",
            "BM ÇORBA BROKOLİ 75GRX12X6",
            "BM SOĞUK ÇORBA AYRAN AŞI 75GRX12X6",
            "BM SOĞUK DEREOTLU KESME ÇORBASI 90GX12X6",
            "BM SPESİYAL TAVUKLU YEŞIL MERC.ÇOR. 96GRX6X12",
            "BM SPESİYAL KÖFTELI KÖY ÇOR. 100GX6X12",
            "BM SPESİYAL NEFASET'IN KOFTELİ SOĞUK ÇOR. 103GX6X12",
            "BM ÖZEL ÇORBA",
            "PİYALE GENDİME YÖRESEL ÇORBA",
            "PİYALE ERİŞTE YÖRESEL ÇORBA",
            "PİYALE ÖZEL ÇORBA",
            "BİZİM MUTFAK 2 KİŞİLİK EZOGELİN ÇORBASI 5x200GRx6",
            "BİZİM MUTFAK 2KİŞİLİK KREMALI TAVUK ÇORBASI 5x155",
            "2 KİŞİLİK ÇORBA",
            "BİZİM MUTFAK HIZLI ACILI EZOGELİN ÇORBASI (YENİ)",
            "BİZİM MUTFAK HIZLI ACILI DOMATES ÇORBASI (YENİ)",
            "BİZİM MUTFAK HIZLI YAYLA ÇORBASI (YENİ)",
            "BM KITIRLI DOMATES",
            "BM KITIRLI KREMALI TAVUK",
            "BM KITIRLI KREMALI MANTAR",
            "BM KITIRLI MERCİMEK",
            "BM HIZLI ÇORBA MULTIPACK DOMATES 88GR",
            "BM HIZLI ÇORBA MULTIPACK MERCİMEK 100 GR",
            "BM HIZLI ÇORBA MULTIPACK K.TAVUK 84 GR",
            "BM HIZLI ÇORBA MULTIPACK K.MANTAR 92 GR",
            "BM KITIRLI  ÇORBA",
            "420 g KETÇAP EV TİPİ",
            "800 g KETÇAP EV TİPİ",
            "BİZİM MUTFAK KETÇAP 800GRX12 YENİ DZY",
            "800 g KETÇAP EV TİPİ SOSLUK",
            "420 g ACILI KETÇAP EV TİPİ",
            "800 g ACILI KETÇAP EV TİPİ",
            "BİZİM MUTFAK ACILI KETÇAP 800Gx12 YENİ DZY",
            "800 g ACILI KETÇAP EV TİPİ SOSLUK",
            "420 g KETÇAP+365 g MAYONEZ İKİLİ ÜRÜN",
            "KETÇAP",
            "250 g CAM MAYONEZ EV TİPİ",
            "500 GR CAM MAYONEZ EV TİPİ",
            "365 g MAYONEZ EV TİPİ",
            "670 g MAYONEZ EV TİPİ",
            "670 g MAYONEZ SOSLUK",
            "670 g MAYONEZ YENİ DİZAYN",
            "MAYONEZ",
            "BM 2 Lİ TAVUK BULYON",
            "BM TAVUK BULYON 5+1 Lİ",
            "BM 9+3 TAVUK BULYON",
            "BM TAVUK BULYON 24'lü",
            "BM TABLET BULYON TAVUK",
            "PİYALE  5+1 TAVUK BULYON",
            "PİYALE 5+1 TAVUK BULYON (ŞARJÖR STAND)",
            "PİYALE  9+3 TAVUK BULYON",
            "PİYALE 24'LÜ TAVUK BULYON",
            "PİYALE TABLET BULYON TAVUK",
            "BM 2 Lİ ET BULYON",
            "BM ET BULYON 5+1 Lİ",
            "BM 9+3 ET BULYON",
            "BM ET BULYON 24'lü ",
            "BM 9+3 BULYON KARMA STAND KOLİ",
            "BM TABLET BULYON ET",
            "PİYALE  5+1 ET BULYON",
            "PİYALE 5+1 ET BULYON (ŞARJÖR STAND)",
            "PİYALE  9+3 ET BULYON",
            "PİYALE 24'LÜ ET BULYON",
            "PİYALE TABLET BULYON ET",
            "BM KÖFTE HARCI BİZİM MUTFAK ( yeni )",
            "BM ÇITIR TAVUK PANE HARCI ( yeni )",
            "BM İNEGÖL KÖFTE HARCI",
            "BM SUCUK KÖFTE HARCI",
            "BM HARÇ KARMA KOLİ",
            "BM HARÇLAR",
            "PİYALE KÖFTE HARCI",
            "PİYALE HARÇLAR",
            "BİZİM MUTFAK TURŞU YAP",
            "KOLAY TURŞU KARIŞIMI",
            "1 KG. BİZİM MUTFAK UN",
            "2 KG. BİZİM MUTFAK UN",
            "4 KG. BİZİM MUTFAK UN",
            "5 KG. BİZİM MUTFAK UN OTURAN POŞET",
            "10 KG. BİZİM MUTFAK UN",
            "BM UN",
            "PİYALE LÜKS UN 12 * 1 KG ",
            "PİYALE LÜKS UN 6 * 2 KG",
            "PİYALE LÜKS UN 3 * 5 KG",
            "PİYALE LÜKS UN 10*2 KG.",
            "PİYALE UN",
            "BİZİM MUTFAK 7 TAHILLI EKMEK UNU",
            "BİZİM MUTFAK ÇAVDARLI EKMEK UNU",
            "BİZİM MUTFAK KÖY EKMEĞİ EKMEK UNU",
            "BİZİM MUTFAK TAM BUĞDAY UNU",
            "BM EKMEKLİK UN",
            "PİYALE KÖY EKMEĞİ UN KARIŞIMI",
            "PİYALE 7 TAHILLI UN KARIŞIMI",
            "PİYALE ÇAVDAR EKMEĞİ UN KARIŞIMI",
            "PİYALE EKMEKLİK UN",
            "BİZİM MUTFAK  5'Lİ ŞEKERLİ VANİLİN (Yeni Ambalaj )",
            "BİZİM MUTFAK  10+2 ŞEKERLİ VANİLİN (Yeni Ambalaj )",
            "BM VANİLİN",
            "PİYALE ŞEKERLİ VANİLİN 5 GR.(5'Lİ)",
            "PİYALE VANİLİN",
            "BİZİM MUTFAK  5'Lİ KABARTMA TOZU (Yeni Ambalaj )",
            "BİZİM MUTFAK  10+2 ŞEKERLİ KABARTMA TOZU (Yeni Ambalaj )",
            "10+2 K. TOZU (81 AD.) +VANİLİN (36 AD.) STANDLI KOLİ",
            "BM KABARTMA TOZU",
            "PİYALE HAMUR KABARTMA TOZU 10 GR.(5'Lİ)",
            "PİYALE KABARTMA TOZU",
            "BİZİM MUTFAK KAKAO 25 GR",
            "BİZİM MUTFAK KAKAO 50 GR",
            "BİZİM MUTFAK KAKAO 100 GR",
            "BM KAKAO",
            "PİYALE DAMLA ÇİKOLATA ",
            "PİYALE KAKAO 25 GR.",
            "PİYALE KAKAO 50 GR.",
            "PİYALE ÇİKOLATA VE KAKAO",
            "BM 250 g PİRİNÇ UNU",
            "BM 500 g PİRİNÇ UNU",
            "BM PİRİNÇ UNU",
            "PİYALE PİRİNC UNU SADE 250 GR",
            "PİYALE PİRİNC UNU VANİLİNLİ 250 GR",
            "PİYALE PİRİNC UNU VİTAMİNLİ 250 GR",
            "PİYALE PİRİNÇ UNU",
            "BM BUĞDAY NİŞASTASI BİZİM MUTFAK",
            "BM MISIR NİŞASTASI BİZİM MUTFAK",
            "BM NİŞASTA",
            "PİYALE BUGDAY NİSASTASİ 200 GR.TİC",
            "PİYALE MİSİR NİSASTASİ 200 GR",
            "PİYALE NİŞASTA",
            "BM PUDRA ŞEKERİ BİZİM MUTFAK",
            "BM PUDRA ŞEKERİ",
            "PİYALE PUDRA ŞEKERİ",
            "PİYALE PUDRA ŞEKERİ",
            "BM PATATES PÜRESİ BİZİM MUTFAK TEKLİ POŞET",
            "BM PÜRE ",
            "PİYALE PATATES PÜRESİ",
            "PİYALE PEYNİRLİ MAKARNA SOS ",
            "PİYALE KR.MANTAR MAKARNA SOS",
            "PİYALE ÇİKOLATA SOS 24*128 GR.",
            "PİYALE ÇİKOLATA SOS 72*128 GR.",
            "PİYALE PÜRE VE MAKARNA SOSLARI",
            "BİZİM MUTFAK KREP 165 GR.",
            "BM KREP",
            "SOYA KIYMASI",
            "SOYA KIYMASI STANDLI KOLİ",
            "SOYA KIYMASI DİSPLAY KOLİ",
            "SOYET SOYA KIYM.350G*8Lİ KARTON DISPLAY STAND",
            "SOYET SOYA KIYM.350G*18Lİ AYAKLI STAND",
            "SOYA KIYMASI ",
            "BİZİM MUTFAK MAKARNA ARPA ŞEHRİYELİ 500GR*20",
            "BİZİM MUTFAK MAKARNA TEL ŞEHRİYE 500GR*20",
            "BİZİM MUTFAK MAKARNA BURGU 500GR*20",
            "BİZİM MUTFAK MAKARNA İNCE UZUN 500GR*20",
            "BİZİM MUTFAK MAKARNA FİYONK 500GR*20",
            "BİZİM MUTFAK MAKARNA KELEBEK 500GR*20",
            "BİZİM MUTFAK MAKARNA SPAGETTİ 500GR*20",
            "BİZİM MUTFAK YÜKSÜK MAKARNA  ",
            "BİZİM MUTFAK BONCUK MAKARNA  ",
            "BİZİM MUTFAK MANTI MAKARNA  ",
            "BİZİM MUTFAK KALEM MAKARNA  ",
            "BİZİM MUTFAK HELEZON MAKARNA  ",
            "BİZİM MUTFAK DİRSEK MAKARNA  ",
            "BİZİM MUTFAK EV ERİŞTESİ ",
            "BİZİM MUTFAK KUSKUS MAKARNA  ",
            "BİZİM MUTFAK TEL ŞEHRİYE ",
            "BİZİM MUTFAK SPAGETTİ MAKARNA  ",
            "BİZİM MUTFAK ARPA ŞEHRIYE ",
            "BİZİM MUTFAK İNCE UZUN MAKARNA  ",
            "BİZİM MUTFAK FİYONK MAKARNA  ",
            "BİZİM MUTFAK BURGU MAKARNA  ",
            "BM.MAKARNA BURGU 1 KG      ",
            "BM.MAKARNA İNCE UZUN 1 KG",
            "BM.MAKARNA YÜKSÜK  1 KG         ",
            "BM.MAKARNA 4X250 GR BURGU",
            "BM MAKARNA",
            "PİYALE ARPA ŞEHRİYE 500 GR.                              ",
            "PİYALE TEL ŞEHRİYE 500 GR.                               ",
            "PİYALE KUSKUS 500 GR.                                    ",
            "PİYALE BONCUK 500 GR.                                    ",
            "PİYALE EV ERİŞTE 500 GR.                                 ",
            "PİYALE İNCEDÜZ 500 GR.                                   ",
            "PİYALE BURGU 500 GR.                                     ",
            "PİYALE B.TIRTIL/YÜKSÜK 500 GR.                                  ",
            "PİYALE K.TIRTIL/İNCE UZUN  500 GR.                                  ",
            "PİYALE MANTI 500 GR.                                     ",
            "PİYALE KALEM 500 GR.                                     ",
            "PİYALE BUKLE/HELEZON 500 GR.                                     ",
            "PİYALE SPAGHETTİ 500 GR.                                 ",
            "PİYALE FİYONK 500 GR.                                    ",
            "PİYALE KELEBEK 500 GR.                                   ",
            "PİYALE KEPEKLİ BURGU",
            "PİYALE ARPA ŞEHRİYE DÖKME 1*5 KG                         ",
            "PİYALE TEL ŞEHRİYE DÖKME 1*5 KG                          ",
            "PİYALE BURGU DÖKME 1*5 KG                                ",
            "PİYALE K.TIRTIL/İNCE UZUN DÖKME 1*5 KG                             ",
            "PİYALE FİYONK DÖKME 1*5 KG                               ",
            "PİYALE SPAGHETTİ DÖKME 1*5 KG                              ",
            "PİYALE KUSKUS DÖKME 1 * 5 KG",
            "PİYALE KALEM MAKARNA 1 * 5 KG.",
            "PİYALE ERİŞTE DÖKME 1 * 5 KG",
            "PİYALE MANTI MAKARNA 1 * 5 KG.",
            "PİYALE BONCUK DÖKME 1 * 5 KG",
            "PİYALE MAKARNA",
            "PİYALE İRMİK 500 GR",
            "PİYALE İRMİK",
            "BİZİM MUTFAK UZ.TANE BALDO PİRİNÇ ",
            "BİZİM MUTFAK UZ.TANE BALDO PİRİNÇ ",
            "BİZİM MUTFAK UZ.TANE OSMAN PİRİNÇ",
            "BİZİM MUTFAK UZ.TANE OSMAN.PİRİNÇ ",
            "BİZİM MUTFAK KIRIK PİRİNÇ ",
            "BİZİM MUTFAK UZ.TANE EL PASO PİRİNÇ",
            "BİZİM MUTFAK UZ.TANE EL PASO PİRİNÇ",
            "BİZİM MUTFAK PİLAVLIK BULGUR ",
            "BİZİM MUTFAK PİLAVLIK BULGUR ",
            "BİZİM MUTFAK KÖFTELİK BULGUR ",
            "BİZİM MUTFAK KIRMIZI MERCİMEK ",
            "BİZİM MUTFAK KIRMIZI MERCİMEK ",
            "BİZİM MUTFAK YEŞİL MERCİMEK ",
            "BİZİM MUTFAK DERMASON FASULYE ",
            "BİZİM MUTFAK DERMASON FASULYE ",
            "BİZİM MUTFAK NOHUT",
            "BİZİM MUTFAK BARBUNYA ",
            "BM BAKLİYAT",
            "BULGUR PİLAVLİK 1000 GR",
            "BULGUR KÖFTELİK 1000 GR",
            "PİYALE BAKLİYAT",
            "180 g ALPELLA KREM",
            "100 gALP. KREM KÜVET",
            "40 g ALPELLA KREM TÜP",
            "450 g ALP KREM ",
            "500 g ALP KREM EKONOMİK",
            "325 gALPELLA KREM IML KASE",
            "650 g ALPELLA KREM IML KASE",
            "750 G ALPELLA KREM ÇİKOLATA",
            "300 GR. ALPELLA KREM ÇİKOLATA",
            "ALPELLA KREM",
            "ALPELLA 3GEN GOFRET FINDIKLI",
            "ALPELLA 3GEN GOFRET BEYAZ",
            "ALPELLA 3GEN GOFRET BİTTER",
            "ALPELLA 3GEN GOFRET TEZGAHÜSTÜ STAND",
            "ALPELLA 3GEN GOFRET",
            "ALPELLA 3GEN GOFRET FINDIKLI M.P.",
            "ALPELLA 3GEN GOFRET BEYAZ  M.P.",
            "ALPELLA 3GEN GOFRET BİTTER  M.P.",
            "ALPELLA 3GEN GOFRET ÇOKLU PAKET",
            "ALPELLA ONE",
            "ALPELLA ONE",
            "ALPELL HARBY",
            "ALPELLA ÇOKOMİLK",
            "ALPELLA ÇOKOMİLK 4 LÜ",
            "ALPELLA ÇOKOMİLK KARAMEL",
            "ALPELLA ÇOKOMİLK KARAMEL 4 LÜ",
            "ALPELLA ÇOKOMİLK",
            "ALPELLA RİNG",
            "ALPELLA RULLO SÜTLÜ",
            "ALPELLA RULLO SÜTLÜ",
            "ALPELLA RULLO ÇİK.",
            "ALPELLA RULLO ÇİK.",
            "ALPELLA KAPLAMA",
            "ALPELLA KAP. KK + YELEK HED.",
            "ALPELTANE",
            "ALPELLA MİNİ BATON SÜTLÜ ÇİKOLATA 23GR",
            "ALPELLA BATON SÜTLÜ ÇİKOLATA 35GR",
            "ALPELLA BATON KIRIK FINDIKLI ÇİKOLATA 35GR",
            "ALPELLA BATON ÇIKOLATA ANTEPFISTIKLI 35GR",
            "ALPELLA BATON FINDIK KREMALI ÇİKOLATA 38GR",
            "ALPELLA BATON BOL SÜTLÜ KARAMELLI 38GR",
            "ALPELLA BATON",
            "ALPELLA TABLET SÜTLÜ ÇİKOLATA 72GR",
            "ALPELLA TABLET KIRIK FINDIKLI ÇİKOLATA 72GR",
            "ALPELLA TABLET FINDIK KREMALI ÇİKOLATA 100GR",
            "ALPELLA TABLET BOL SÜTLÜ KARAMELLI 100GR                                                          ",
            "40g ALPELLA BALMOND",
            "100g ALPELLA BALMOND",
            "ALPELLA SÜTLÜ TABLET YENİ",
            "ALPELLA FINDIKLI SÜTLÜ TABLET YENİ",
            "ALPELLA ANTEP FISTIKLI TABLET YENİ",
            "80 GR ALPELLA DARK BİTTER TABLET YENİ",
            "100 GR ALPELLA ÇİFTE KARAMELLİ TABLET YENİ",
            "ALPELLA TABLET",
            "ALPELLA RIO SÜTLÜ KARE ÇIKOLATA 55GR",
            "ALPELLA RIO BÜTÜN FINDIKLI KARE ÇİKOLATA 55GR",
            "ALPELLA RIO  BADEMLİ KARE ÇİKOLATA 55GR",
            "ALPELLA RIO BÜTÜN ANTEPFISTIKLI KARE ÇİKOLATA 55GR",
            "ALPELLA RIO BÜTÜN FINDIKLI BİTTER KARE ÇİKOLATA 55GR",
            "ALPELLA RİO BADEMLİ",
            "ALPELLA RİO FINDIKLI",
            "ALPELLA RİO ANTEP FISTIKLI",
            "ALPELLA RİO FINDIKLI ÜZÜMLÜ",
            "ALPELLA RİO BİTTER FINDIKLI",
            "ALPELLA RİO BİTTER ANTEP FISTIKLI",
            "ALPELLA RİO BATON FINDIKLI",
            "ALPELLA RİO BATON KARAMEL FINDIKLI",
            "ALPELLA RİO BATON ANTEP FISTIKLI",
            "ALPELLA RİO",
            "ALPELLA KARE SÜTLÜ ÇİKOLATA 55GR",
            "ALPELLA KARE BOL SÜTLÜ FINDIK KREMALI ÇİKOLATA 60GR",
            "ALPELLA KARE BOL SÜTLÜ KARAMELLİ 60GR",
            "ALPELLA KARE BOL SÜTLÜ HİNDİSTAN CEVİZLİ ÇİK.60GR",
            "ALPELLA KARE BOL SÜTLÜ BİSKÜVİLİ ÇİKOLATA 60GR",
            "ALPELLA KARE",
            "ALPELLA RİVA H.CEVİZİ DOL. KARE ÇİK",
            "ALPELLA RİVA BİSKÜVİ DOL. KARE ÇİK.",
            "ALPELLA RİVA ÇİK.RÜYASI. KARE ÇİK.",
            "ALPELLA RİVA LATTE KREMASI DOL. KARE ÇİK.",
            "ALPELLA RİVA",
            "ALPELLA RİVA H.CEVİZİ DOL.ÇİK",
            "ALPELLA RİVA ÇİK.RÜYASI.ÇİK.",
            "ALPELLA RİVA LATTE KREMASI DOL.ÇİK.",
            "ALPELLA RİVA 45GR",
            "ALPELLA FİŞEK SÜTLÜ ÇİKOLATA 50GR",
            "ALPELLA FİŞEK KARAMELLİ ÇİKOLATA 50GR",
            "ALPELLA OLE KARAMEL DOLGULU ÇİKOLATA",
            "ALPELLA OLE PORTAKALLI ÇİKOLATA",
            "ALPELLA OLE H.CEVİZİ DOLGULU ÇİKOLATA",
            "ALPELLA OLE",
            "ALPELLA MİNİ RULO PASTA",
            "ALPELLA MİNİ RULO PASTA MUZLU",
            "ALPELLA ÇİKOLATALI MİNİ RULO PASTA",
            "ALPELLA KREMALI KEK",
            "ALPELLA SADE KEK",
            "DİLİM KEK",
            "ALPELLA VİŞNE KREMALI KEK 45GRX24",
            "ALPELLA ÇİLEK KREMALI KEK 45GRX24",
            "ALPELLA ÇİKOLATA KREMALI KEK 45GRx24",
            "ALPELLA SÜT KREMALI KEK 45GRX24",
            "YENİ ALPELLA VİŞNELİ MUFFİN KEK 45 GR.X24X4",
            "YENİ ALPELLA ÇİLEKLİ MUFFİN KEK 45 GR.X24X4",
            "YENİ ALPELLA ÇİKOLATALI MUFFİN KEK 45 GR.X24X4",
            "YENİ ALPELLA SÜT KREMALI MUFFİN KEK 45GR.X24X4",
            "ALPELLA VİŞNE KREMALI KEK 40GRx24",
            "ALPELLA ÇİKOLATA KREMALI KEK 40GRx24",
            "ALPELLA SÜT KREMALI KEK 40GRx24",
            "YENİ ALPELLA 45 GR MUFFİN KEK",
            "ALPELLA CHUNKY KEK KAKAOFIND.40GRx24x4",
            "ALPELLA CHUNKY KEK HAVUÇ.TARÇIN43GRx24x4",
            "ALPELLA CHUNKY KEK KARMA KOLİ",
            "ALPELLA CHUNKY KEK",
            "ALPELLA İKİ RENKLİ PÖTİBÖR",
            "ALPELLA İKİ RENKLİ PÖTİBÖR",
            "ALPELLA İKİ RENKLİ PÖTİBÖR",
            "ALPELLA İKİ RENKLİ PÖTİBÖR",
            "ALPELLA BİSKÜVİ",
            "COCO POPS TOPLARI 100GRX36",
            "COCO POPS TOPLARI 250 GR",
            "250 GR COCO POPS ÇITIRLARI POŞET",
            "250GR COCOPOPS ÇOKOTOP",
            "COCOPOPS TOPLARI 375 GR",
            "COCO POPS TOPLARI 500GR",
            "COCOPOPS ÇOKOTOP 500GRX10",
            "COCOPOPS TOP 500GRX10 COCO KASE HEDİYELİ          ",
            "COCO POPS TOPLARI 2x500GR 2.%50 BEDAVA",
            "COCO POPS TOPLARI 750 GR*10",
            "HONEY POPS BALLI MISIR GEVREĞİ 250GRx10",
            "HONEY POPS BALLI MISIR GEVREĞİ 500GRx10",
            "TAHIL GEVREKLERİ ÇOCUK",
            "K-FLAKES SADE 250 GR",
            "K-FLAKES ÇİKOLATALI 250GR",
            "K-FLAKES KIRMIZI 250 GR",
            "SPECIAL K KARIŞIK MEYVELİ 250GRx10",
            "K FLAKES SADE 500 GRX10",
            "SPECIAL K FLAKES ÇIKOLATALI 500GRX10",
            "SPECIAL K FLAKES KIRMIZI MEYVELI500GRX10",
            "SPECIAL K KARIŞIK MEYVELİ 500GRx10",
            "K FLAKES SADE 2X500GRX5 2.%50 BEDAVA",
            "TAHIL GEVREKLERİ YETİŞKİN",
            "CORN FLAKES MISIR GEVREĞI ",
            "CORN FLAKES MISIR GEVREĞI ",
            "HONEY LOOPS BALLI TAHIL GEVREĞI ",
            "TAHIL GEVREKLERİ AİLE",
            "COCO POPS BAR",
            "COCO POPS BAR MP",
            "COCO POPS BAR MP OYUNCAK HED.",
            "COCO POPS ÇOKOTOP BAR",
            "COCO POPS ÇOKOTOP BAR MP",
            "TAHIL BARLARI ÇOCUK",
            "K-BAR VIŞNELI",
            "K-BAR ŞEFTALILI KAYSILI",
            "K-BAR ÇIKOLATALI",
            "K-BAR VIŞNELI MP",
            "K-BAR ŞEFTALILI KAYISILI MP ",
            "K-BAR ÇIKOLATALI MP ",
            "SPECIAL K BAR ŞEFT.KAY.3AL2ÖDE 3x21GRx36",
            "SPECIAL K BAR ÇİKOLATA.3AL2ÖDE 3x21GRx36",
            "TAHIL BARLARI YETİŞKİN",
            "DOĞA®  MEYVELİ YULAF GEVREĞİ",
            "DOĞA NUTRİDİGEST ® SOYALI ÇITIR MÜSLİ",
            "DOĞA NUTRİDİGEST ® KETEN TOHUMLU MÜSLİ",
            "DOĞA NUTRİDİGEST ® GLUTENSİZ MÜSLİ",
            "DOĞA NUTRİDİGEST ® BALLI GRANOLA ÇITIR MÜSLİ",
            "DOĞA NUTRİDİGEST ® PARÇA ÇİKOLATALI MÜSLİ",
            "DOĞA NUTRİDİGEST ® PREBİYOTİK MÜSLİ",
            "PROACVTİVE PROBİYOTİK TAHIL GEVREĞİ",
            "DOĞA MÜSLİ ",
            "DOĞA NUTRİDİGEST ® BUĞDAY EZMESİ",
            "DOĞA® YULAF EZMESİ",
            "DOĞA® KEPEK",
            "DOĞA TAHIL EZMELERİ",
            "DOĞA NUTRİDİGEST ® FINDIKLI MÜSLİ BAR 24'LÜ KUTU",
            "DOĞA NUTRİDİGEST ® KETEN TOHUMLU  MÜSLİ BAR  24'LÜ KUTU",
            "DOĞA NUTRİDİGEST ® YEŞİL ÇAYLI MÜSLİ BAR  24'LÜ KUTU",
            "DOĞA NUTRİDİGEST ® FINDIKLI MÜSLİ BAR  6'LI KUTU",
            "DOĞA NUTRİDİGEST ® KETEN TOHUMLU  MÜSLİ BAR  6'LI KUTU",
            "DOĞA NUTRİDİGEST ® YEŞİL ÇAYLI MÜSLİ BAR  6'LI KUTU",
            "DOĞA MÜSLİ BAR",
            "SUPER TON 3x80 GRx8",
            "SUPER TON 2x160 GRx12",
            "SUPER TON 1000 GRx6",
            "SUPERTON  PROM.2ADET(160G TON BALIĞI + 2 ADET 220G MISIR) ",
            "SÜPERTON",
            "KALBİM  TON BALIĞI 80 X3",
            "KALBİM  TON BALIĞI 160 X2",
            "KALBİM LİGHT TON BALIĞI 80 X 3",
            "KALBİM LİGHT TON BALIĞI 160 X 2",
            "KALBİM TON",
            "DOMATES SOSLU SUPERFRESH USKUMRU",
            "KARABİBERLİ SUPERFRESH USKUMRU",
            "SÜPERFRESH USKUMRU",
            "SUPER FRESH MISIR 220 GRx24",
            "SUPER FRESH MISIR 3x220 GRx15",
            "SUPER FRESH MISIR 600 GRx12",
            "SUPER FRESH MISIR 425 GRx12",
            "SÜPERFRESH MISIR KONSERVESİ",
            "SUPER FRESH MANTAR BÜTÜN 330 GRx12",
            "SUPER FRESH MANTAR KIYILMIŞ 330 GRx12",
            "SUPER FRESH GARNİTÜR 330 GRx12",
            "SUPER FRESH GARNİTÜR 570 GRx12",
            "SUPER FRESH KÖZ.BİBER 650 GRx12",
            "SUPER FRESH BEZELYE (TENEKE) 830 GRx12",
            "SÜPERFRESH SEBZE KONSERVESİ",
            "HOBBY KAK.FIN.KREMA DOL.360 GR.SÜTLÜ KOKOLİN ",
            "HOBBY ÇİKOLATİN 3 KG.DÖKME  ",
            "MİNİ HOBBY* ikramlık satılmaktadır.",
            "HOBBY 2Lİ",
            "HOBBY",
            "HOBBY 5' Lİ",
            "HOBBY MİNİ TABLET",
            "HOBBY",
            "HOBBY KAPLAMALI KREMALI KEK",
            "HOBBY KAKAOLU FINDIKLI KEK",
            "HOBBY MOZAİK KEK",
            "HOBBY SÜTLÜ KOKO.KAPL.FIND.KREMALI KEK 30GRx40",
            "HOBBY SÜTLÜ KOKO.KAPL.FIND.KAKAOLU KEK 30GRx40",
            "HOBBY SÜTLÜ KOKOLİN KAPL.MOZAİK KEK 30GRx40",
            "HOBBY  KEK",
            "HOBBY KAPLAMALI GOFRET",
            "HOBBY  GOFRET",
            "HOBBY KAPL.SANDVİÇ BİSK.28GRx24x6",
            "HOBBY SANDVİÇ BİSKÜVİ",
            "HOBBY KREM ÇİKOLATA",
            "HOBBY  KREM ÇİKOLATA",
            "HOBBY MARSMALLOV",
            "HOBBY  MARSMALLOV",
            "ÇOKOMEL ÇİK.KAP.PİRİNÇ PATLAKLI BAR ",
            "ÇOKOMEL ÇİLEKLİ (3'LÜ)",
            "ÇOKOMEL MUZLU (3'LÜ)",
            "ÇOKOMEL SADE (3'LÜ)",
            "ÇOKOMEL SADE (9'LU)",
            "ÇOKOMEL ÇİLEKLİ (9'LU)",
            "ÇOKOMEL SADE (40'LI KAVANOZ)",
            "ÇOKOMEL ÇİLEKLİ (40'LI KAVANOZ)",
            "ÇOKOMEL MUZLU (40'LI KAVANOZ)",
            "ÇOKOMEL",
            "ÇOKOMEL POFTİ KAKOLU       ",
            "ÇOKOMEL POFTİ HİNDİSTANCEVİZLİ",
            "ÇOKOMEL POFTİ MUZLU",
            "ÇOKOMEL POFTİ ÇİLEKLİ",
            "ÇOKOMEL POFTİ KAKOLU 8'Lİ",
            "ÇOKOMEL  POFTİ",
            "ÜLKER ÇOKOPRENS TURTA PORT.JÖL - TEK LOKMALIK",
            "ÜLKER ÇOKOPRENS TURTA PORT.JÖLELİ - TEKLİ PAKET",
            "ÜLKER ÇOKOPRENS TURTA PORT.JÖLELİ - BÜYÜK PAKET",
            "ÇOKOPRENS",
            "BİANKO GOFRET",
            "BİANKO CREAM GOFRET",
            "BİANKO",
            "KİNG TOP KAPLAMALI GOFRET (3'LÜ TOP)",
            "KİNG TOP KAPLAMALI GOFRET (3'LÜ TOP) ASKILI",
            "KİNG TOP 20'Lİ DEFİNE KUTU",
            "KİNG TOP 35'Lİ İKRAMLIK KUTU",
            "KINGTOP DEFİNE STAND KOLİ(BAZALI) ESKİ",
            "KINGTOP DEFİNE STAND KOLİ(BAZALI) YENİ",
            "KİNG TOP",
            "CHAT",
            "ÜLKER GOLDEN BİTTER DRAJE FINDIKLI",
            "ÜLKER GOLDEN BİTTER DRAJE FISTIKLI",
            "ÜLKER GOLDEN BİTTER DRAJE ÜZÜMLÜ",
            "ÜLKER GOLDEN BİTTER DRAJE PORTAKALLI",
            "ÜLKER GOLDEN BİTTER DRAJE BADEMLİ",
            "GOLDEN  DRAJE",
            "ÇOKOMİSKET PİRİNÇ PAT.DRAJE 50GX12X6  ",
            "ÇOKOMİSKET FINDIK DRAJE 50GRX12X6",
            "ÇOKOMİSKET PİRİNÇ P.DRAJE 50GX6X12 ASKILI",
            "ÇOKOMİSKET FIN.DRAJE 50GX6X12 ASKILI",
            "ÇOKOMİSKET",
            "ÜLKER KREMALI SANDVİÇ BİSKÜVİ 75GRX30 ",
            "ÜLKER KREMALI SANDVİÇ BİSKÜVİ 4x75GRX15",
            "ÜLKER KREMALI SANDVİÇ BİSKÜVİ 10x75grx8",
            "ÜLKER KREMALI SANDVİÇ BİSKÜVİ",
            "KREMİNİ PORTAKALLI  ",
            "KREMİNİ ÇİLEKLİ      ",
            "KREMİNİ AHUDUDULU      ",
            "KREMİNİ VİŞNELİ       ",
            "KREMİNİ SÜTLÜ",
            "KREMİNİ DAMLA SAKIZLI",
            "KREMİNİ İKİZ LEZZET VİŞNE - PORTAKAL (12'Lİ)",
            "KREMİNİ İKİZ LEZZET ARMUT - KAVUN (12'Lİ)",
            "KREMİNİ ASETAT",
            "KREMİNİ TOFFE",
            "KREMİNİ MEY.PASTA DOLGULU JELLY 60GX24",
            "KREMİNİ JELLY TURUNÇGİLLER 60GX24",
            "KREMİNİ JELLY AHUDUDU 60GX24",
            "KREMİNİ JELLY MEYVE SEPETİ 60GX24",
            "KREMİNİ JELLY",
            "KREMİNİ LOLİPOP KARMA ASETAT 960GRX6",
            "KREMİNİ LOLİPOP  ",
            "KREMİNİ SÜTLÜ ÇİLEKLİ BONBON 40GRx24x12",
            "KREMİNİ SÜTLÜ PORT.BONBON 40GRx24x12",
            "KREMİNİ BONBON",
            "KREMİNİ ÇİLEKLİ DRAJE TOFFE 31,5Gx12x6",
            "KREMİNİ ŞEFTALİLİ DRAJE TOFFE 31,5Gx12x6",
            "KREMİNİ DRAJE TOFFE",
            "KREMİNİ DOLGULU KAR.MEYV.TOFFE 65GRx24",
            "KREMİNİ DRAJE TOFFE",
            "KREMİNİ KARMA T.ÜSTÜ STAND 3,8KGX4",
            "KREMİNİ TEZGAÜSTÜ STAND",
            "STARS ASETAT",
            "STARS",
            "BONBON MEYVELİ RULO ŞEKER ",
            "BONBON NANELİ RULO ŞEKER        ",
            "BONBON LİMONLU RULO ŞEKER",
            "BONBON",
            "YUPO AYICIK 20 GR",
            "YUPO KOLALI 20 GR",
            "YUPO AYICIKLI 30 GR",
            "YUPO MEYVE BAHÇESİ 30 GR",
            "YUP KOLALI 30 GR",
            "YUPO SOLUCAN 25 GR",
            "YUPO JELİTOP 30",
            "YUPO JUNGLE",
            "YUPO JELLY NEŞELİ DİŞLER ",
            "YUPO JELLY RENKLİ HARFLER ",
            "YUPO MUZ",
            "YUPO ASKILI",
            "YUPO AYICIK 65GRx24",
            "YUPO KOLALI 65GRX24",
            "YUPO MEYVE BAHÇESİ 65GRx24",
            "YUPO JUNGLE 65GRx24",
            "YUPO JELİTOP 65GRX24",
            "YUPO RENKLİ HARFLER 65GRx24",
            "YUPO SOLUCAN 65GRx24",
            "YUPO NEŞELİ DİŞLER 65GRx24",
            "YUPO KOLALI 100GRx24",
            "YUPO AYICIK 100GRx24",
            "YUPO JUNGLE 100GRx24",
            "YUPO MEYVE BAHÇESİ 100GRx24",
            "YUPO JELİTOP 100GRx24",
            "YUPO NEŞELİ DİŞLER 100GRx24",
            "YUPO RENKLİ HARFLER 100GRx24",
            "YUPO SOLUCAN 100GRx24",
            "YUPO KOLALI BARDAK 170 GR",
            "YUPO AYICIK BARDAK 170GR",
            "YUPO SOLUCAN BARDAK 170 GR",
            "YUPO JELLY",
            "YUPO KARMA DİSPLAY 30GRX48",
            "YUPO JELLY TEZGAHÜSTÜ STAND",
            "YUPO TOP ŞEKER TEK AROMALI KARMA ASETAT 11GR.",
            "YUPO TOP ŞEKER TEK AROM.KARMA POŞET 11GR.",
            "YUPO LOLLİPOP 16G. SAKIZ DOLGULU KARMA ASETAT",
            "YUPO LOLLİPOP 16GR(5Lİ POŞET) ",
            "YUPO LOLİPOP",
            "VİVA",
            "UFO DRAJE",
            "UFO DRAJE",
            "HOBBY KAKAOLU  DRAJE ŞEKER",
            "HOBBY DRAJE",
            "ÜLKER GALLERY MİNİ BONBON NANE AROMALI-DÖKME",
            "ÜLKER GALLERY MİNİ BONBON MEYVELİ-DÖKME",
            "ÜLKER GALLERY BONBON ÇİLEK / PORTAKAL / ELMA / LİMON",
            "ÜLKER GALLERY BONBON KAHVELİ",
            "ÜLKER GALLERY BONBON SÜTLÜ                                         ",
            "ÜLKER GALLERY BONBON TEREYAĞLI",
            "ÜLKER GALLERY DOLGULU VİŞNE",
            "ÜLKER GALLERY DOLGULU PORTAKAL",
            "ÜLKER GALLERY DOLGULU ÇİLEK",
            "ÜLKER GALLERY DOLGULU  ÇİKOLATALI",
            "ÜLKER GALLERY TOFFE SÜTLÜ",
            "ÜLKER GALLERY TOFFE PORTAKAL",
            "ÜLKER GALLERY TOFFE VİŞNE",
            "ÜLKER GALLERY TOFFE ÇİLEK",
            "ÜLKER GALLERY DAMLA SAKIZLI TOFFE ",
            "GALLERY DÖKME İKRAMLIK",
            "ÜLKER GALLERY BONBON AKİDE - GÜLLÜ",
            "ÜLKER GALLERY BONBON AKİDE - TARÇIN & KARANFİL",
            "ÜLKER GALLERY BONBON AKİDE - DAMLA SAKIZLI",
            "GALLERY AKİDE DÖKME İKRAMLIK",
            "ÜLKER HOBBY DOLGULU TOFFE DOLGULU   ÇİKOLATALI ",
            "ÜLKER HOBBY ÇOKOTOFFE(KAKAO KAPLI KREM FONDON)",
            "HOBBY DÖKME İKRAMLIK",
            "ÜLKER GALLERY MİNİ BONBON MEYVELİ  (POŞET)",
            "ÜLKER GALLERY KARIŞIK AMBALAJ (POŞET) ",
            "ÜLKER GALLERY BONBON  SÜTLÜ",
            "ÜLKER GALLERY BONBON  KARIŞIK MEYVELİ",
            "ÜLKER GALLERY BONBON  KAHVELİ",
            "ÜLKER GALLERY BONBON  SÜTLÜ TEREYAĞLI",
            "ÜLKER GALLERY DOLGULU TOFFE  ÇİKOLATALI",
            "ÜLKER GALLERY DOLGULU TOFFE  KARIŞIK MEYVELİ",
            "ÜLKER GALLERY DAMLA SAKIZI AROMALI ",
            "ÜLKER GALLERY TOFFE  KARIŞIK MEYVELİ",
            "GALLERY POŞET İKRAMLIK",
            "GALERY AKİDE BONBON 350GX10",
            "GALLERY AKİDE POŞET İKRAMLIK",
            "ÜLKER HOBBY TOFFE ÇİKOLATALI",
            "POŞET ÇOKOTOFFE(KAKAO KAPLI KREM FONDAN)",
            "HOBBY POŞET İKRAMLIK",
            "CARAMIO BİTTER ÇİK KAP KARAMEL ŞEK 250GRX10",
            "CARAMİO SÜTLÜ ÇİK KAP KARAMEL ŞEK 250GRX10",
            "CARAMIO POŞET İKRAMLIK",
            "KREMİNİ MEYVELİ DOLGULU TOFFE 350GRX10",
            "KREMİNİ POŞET İKRAMLIK",
            "GALLERY KARIŞIK DOLG.TOFFE ASETAT 1400X6",
            "GALLERY KARIŞIK TOFFE ASETAT 1550GRX6",
            "MİNİ BONBON KARIŞIK MEYVELİ 700 GR.ASETAT  ",
            "ASETAT İKRAMLIK",
            "ONEO NANE AROMALI TAT.DRAJE FLİPTOP KUTU",
            "ONEOYEŞİL NANE AROMALI TAT.DRAJE FLİPTOP KUTU",
            "ONEO DAMLA SAKIZLI AROMALI TAT.DRAJE FLİPTOP KUTU",
            "ONEO ÇİLEK  AROMALI TAT.DRAJE FLİPTOP KUTU",
            "ONEO  TROPİKAL MEYVE  AROMALI TAT.DRAJE FLİPTOP KUTU",
            "ONEO KÜÇÜK STAND",
            "ONEO BÜYÜK STAND",
            "ONEO DOLUMLU OSM STAND",
            "ONEO FLIPTOP SAKIZ",
            "ONEO TROPİK A.LI TAT.DRAJE 2x27GRx10x8",
            "ONEO YEŞİL NANE A.LI TAT.DRA.2x27GRx10x8",
            "ONEO NANE A.LI TAT.DRA.FLİP.2x27GRx10x8",
            "ONEO DAMLA SAK.A.LI TAT.DRA.2x27GRx10x8",
            "ONEO ÇİLEK A.LI TAT.DRA.FLİP.2x27GRx10x8",
            "ONEO MULTIPACK FLIPTOP SAKIZ",
            "ONEO NANE AROMALAI CEP PAKET",
            "ONEO YEŞİL NANE AROMALAI CEP PAKET",
            "ONEO DAMLA AROMALAI CEP PAKET",
            "ONEO ÇİLEK AROMALAI CEP PAKET",
            "ONEO TROPİKAL AROMALAI CEP PAKET",
            "ONEO KÜÇÜK STAND CEP PAKET",
            "ONEO CEP PAKET SAKIZ",
            "ONEO TAT.DR.SAK.Y.NANE RES.BAG 36GRx20x8",
            "ONEO TAT.DR.SAK.ÇİLEK.RES..BAG 36GRx20x8",
            "ONEO  AÇ KAPA PAKET SAKIZ",
            "YILDIZ NANE AROMALI ŞEKERLİ DRAJE SAKIZ",
            "YILDIZ DAMLA SAKIZI AROMALI ŞEKERLİ DRAJE SAKIZ",
            "YILDIZ ÇİLEK AROMA.Ş.Lİ DRAJE SAKIZ 10,4GRX18",
            "YILDIZ ŞEKERLİ DRAJE 4'LÜ MP KARMA ÖSM STAND",
            "YILDIZ SOFT DAMLA SAKIZ AROMALI",
            "YILDIZ SOFT NANE AROMALI",
            "YILDIZ KARBONATLI NANE AROMALI ŞEKERSİZ",
            "YILDIZ SOFT KARMA KAVANOZ 400'LÜ ",
            "YILDIZ NANE AROMALI TATLANDIRICILI DRAJE SAKIZ",
            "YILDIZ DAMLA AROMALI TATLANDIRICILI DRAJE SAKIZ",
            "YILDIZ NANE A.LI TAT.DRA.FLİ.2X21GRX10X8",
            "YILDIZ DAMLA A.LI TAT.DRA.FL.2X21GRX10X8",
            "YILDIZ TATLANDIRICILI BAKKAL STAND",
            "YILDIZ NANE AROMALI ŞEKERLİ DRAJE SAKIZ 4'LÜ MP",
            "YILDIZ DAMLA SAKIZI AROMALI ŞEKERLİ DRAJE SAKIZ 4'LÜ MP",
            "YILDIZ ÇİLEK AROMA.Ş.Lİ DRAJE SAKIZ 10,4GRX18 4'LÜ MP",
            "YILDIZ ŞEKERSİZ DAMLA 10'LU POŞET",
            "YILDIZ SAKIZ",
            "YUPO 300LÜ ASETAT KARMA KAVANOZ",
            "YUPO BENTEN ÇIKARTMA HEDİYELİ KARIŞIK MEYVE AROMALI BALONLU ŞEKERLİ SAKIZ",
            "YUPO-BENTEN TEZGAHÜSTÜ STAND 1542GRx6",
            "YUPO SAKIZ",
            "CHEWY MEYVE-BAHÇESİ-FT 1+1 ",
            "CHEWY BEYAZ-DİŞLER-FT 1+1",
            "CHEWY 2 Sİ 1 ARADA FT 1+1",
            "CHEWY DAMLA TANESİ FT 1+1",
            "CHEWY",
            "DUBİX",
            "BLOW UP",
            "SARAR STREÇ FİLM 15 M",
            "SARAR STREÇ FİLM 33 M",
            "SARAR ALÜMİNYUM FOLYO 10 M",
            "SARAR ALÜMİNYUM FOLYO 15 M",
            "SARAR GIDA MUHAFAZA ",
            "SERA 15M STREÇ FİLM",
            "SERA 33M STREÇ FİLM",
            "SERA 99M STREÇ FİLM",
            "SERA 165M STREÇ FİLM",
            "SERA 8M ALÜMİNYUM FOLYO",
            "SERA 15M ALÜMİNYUM FOLYO",
            "SERA GIDA MUHAFAZA "
        };
    }
}